RESTFUL_HOST = ENV.fetch("RESTFUL_HOST")
RESTFUL_PORT = ENV.fetch("RESTFUL_PORT")
RESTFUL_KEY = ENV.fetch("RESTFUL_KEY")

AUTOCONFIG_TANGO_TIMEOUT = 15
AUTOCONFIG_MAX_DEAD_JOBS = 500
AUTOCONFIG_DEF_DEAD_JOBS = 15
RESTFUL_USE_POLLING = false
